"""Static Cortext agent-pack catalog for Agent Hub routes."""

_CORTEXT_NATIVE_REPLACEMENTS = [
    "daemon -> Elevate desktop backend + agent worker",
    "IPC -> dashboard HTTP/WebSocket APIs",
    "PM2 -> desktop process + heartbeat/cron schedulers",
    "PTY injection -> prompt/tool contracts",
    "file inbox -> Comms, handoffs, Tasks, Activity",
]

# NOTE: "orchestrator" is intentionally NOT an installable pack. The native
# Executive Assistant (agent_hub.DEFAULT_AGENT_DEFS) IS the orchestrator - its
# coordination doctrine was folded into EA's definition. Do not re-add an
# orchestrator pack; it would duplicate EA.
# NOTE: "analyst" and "theta-wave" are also native agents (DEFAULT_AGENT_DEFS),
# so they are NOT installable packs - a pack with the same id collides with the
# built-in on install ("cannot be recreated").
_CORTEXT_AGENT_PACKS = [
    {
        "id": "security",
        "name": "Security",
        "role": "security",
        "emoji": "S",
        "source": "community/agents/security",
        "template": "agent",
        "description": "Security specialist for credential hygiene, risky changes, vulnerability review, and incident response.",
        "owns": ["security", "credentials", "risk-review", "incident-response"],
        "handoff_targets": ["executive-assistant", "admin"],
        "escalation_target": "executive-assistant",
        "day_start": "09:00",
        "day_end": "18:00",
        "day_mode": "Review risky changes, flag credential/config exposure, and keep security work actionable.",
        "night_mode": "Monitor for drift, suspicious changes, stale secrets, and unresolved security tasks.",
        "memory_scopes": ["security", "credentials", "incidents", "approvals"],
        "includes": ["Identity", "Soul", "Guardrails", "Security tasks", "Approval policy"],
    },
    {
        "id": "agentic-crm-assistant",
        "name": "Agentic CRM Assistant",
        "role": "crm",
        "emoji": "C",
        "source": "community/agents/agentic-crm-assistant",
        "description": "CRM assistant with relationship memory, inbox/calendar review, meeting prep, follow-ups, and approval-safe drafts.",
        "owns": ["crm", "relationships", "inbox-triage", "calendar", "follow-ups"],
        "handoff_targets": ["executive-assistant", "admin", "outreach"],
        "escalation_target": "executive-assistant",
        "day_start": "08:00",
        "day_end": "20:00",
        "day_mode": "Triage relationships, prepare meetings, draft replies, and create tasks without sending externally unless approved.",
        "night_mode": "Quietly process notes, reconcile CRM memory, and prepare next-day follow-up options.",
        "memory_scopes": ["crm", "relationships", "meetings", "follow-ups"],
        "includes": ["Identity", "Soul", "CRM memory", "Inbox triage", "Calendar", "Meeting prep", "Follow-ups"],
    },
    {
        "id": "research-agent",
        "name": "Research Agent",
        "role": "research",
        "emoji": "R",
        "source": "community/agents/research-agent",
        "description": "Research specialist for source collection, signal scoring, daily briefs, topic briefings, and trend review.",
        "owns": ["research", "briefs", "signals", "trend-review"],
        "handoff_targets": ["analyst", "executive-assistant"],
        "escalation_target": "analyst",
        "day_start": "09:00",
        "day_end": "18:00",
        "day_mode": "Collect sources, score signals, produce concise briefs, and route delivery through approvals.",
        "night_mode": "Synthesize findings, update research memory, and queue next-day questions.",
        "memory_scopes": ["research", "signals", "briefs", "sources"],
        "includes": ["Identity", "Soul", "Research workflows", "Brief automations", "Memory", "Guardrails"],
    },
    {
        "id": "worker-agent",
        "name": "Worker Agent",
        "role": "worker",
        "emoji": "W",
        "source": "community/agents/agent",
        "template": "agent",
        "description": "General-purpose worker template for specialist agents. Handles assigned tasks, memory, handoffs, and heartbeat checks.",
        "owns": ["assigned-work", "handoffs", "task-execution"],
        "handoff_targets": ["executive-assistant"],
        "escalation_target": "executive-assistant",
        "day_start": "09:00",
        "day_end": "18:00",
        "day_mode": "Work the highest-priority assigned task, communicate blockers, and update task state.",
        "night_mode": "Process safe queued work only, summarize blockers, and avoid external sends.",
        "memory_scopes": ["tasks", "handoffs", "worklog"],
        "includes": ["Identity", "Soul", "Heartbeat", "Tasks", "Comms", "Memory"],
    },
    # Real-estate-native packs (authored for Elevate, not imported from
    # Elevate community). Each ships a complete config.json; no template key on
    # purpose: a template merge would flip runtime_type away from native.
    {
        "id": "compliance-reviewer",
        "name": "Compliance Reviewer",
        "role": "compliance",
        "emoji": "C",
        "source": "community/agents/compliance-reviewer",
        "description": "Deal-file completeness reviewer that checks disclosures, identification, and record-keeping (FINTRAC where applicable in Canada) and flags gaps without fixing them.",
        "owns": ["deal-file-review", "disclosure-checklists", "id-record-keeping-checks", "compliance-flags"],
        "handoff_targets": ["admin", "executive-assistant"],
        "escalation_target": "admin",
        "day_start": "09:00",
        "day_end": "17:00",
        "day_mode": "Review files on cadence, triage new flags, verify resolved flags, and keep the closing-blocker list current.",
        "night_mode": "Pre-stage the next day's review queue and summarize open flags by severity; no external anything, no flag closures.",
        "memory_scopes": ["compliance", "deal-files", "disclosures", "approvals"],
        "includes": ["Identity", "Soul", "Guardrails", "File review", "Disclosure watch", "Flag-don't-fix posture"],
    },
    {
        "id": "sphere-farming",
        "name": "Sphere Farming",
        "role": "sphere",
        "emoji": "F",
        "source": "community/agents/sphere-farming",
        "description": "Sphere and farm program operator: drafts anniversary and milestone touches, market updates for past clients, earned referral asks, and geographic-farm sequences.",
        "owns": ["past-client-touches", "anniversary-milestones", "referral-asks", "geo-farm-sequences"],
        "handoff_targets": ["outreach", "marketing"],
        "escalation_target": "outreach",
        "day_start": "09:00",
        "day_end": "18:00",
        "day_mode": "Draft today's due touches, advance farm sequences, queue earned referral asks, and keep the touch calendar honest.",
        "night_mode": "Pre-draft upcoming anniversaries and market updates and refresh farm-sequence schedules; no sends or program changes.",
        "memory_scopes": ["sphere", "past-clients", "referrals", "farm"],
        "includes": ["Identity", "Soul", "Guardrails", "Touch calendar", "Farm sequences", "Referral asks"],
    },
]
