import type { CrmIntegrationForm } from "@/lib/api";

export interface CrmPreset {
  slug: string;
  label: string;
  description: string;
  helpUrl: string;
  helpText: string;
  keyLabel: string;
  logo: string;
  notice?: string;
  template: Omit<CrmIntegrationForm, "apiKey" | "hasApiKey" | "apiKeyPreview">;
}

const base = {
  hasApiKey: false as const,
  apiKeyPreview: null,
};

export const CRM_PRESETS: CrmPreset[] = [
  {
    slug: "lofty",
    label: "Lofty",
    description: "Lofty CRM (formerly Chime). Authorization: token <key>.",
    helpUrl: "https://help.lofty.com/hc/en-us/articles/47499531505179",
    helpText: "Settings → Integrations → API on each user account.",
    keyLabel: "Lofty API Key",
    logo: "https://logo.clearbit.com/lofty.com",
    template: {
      provider: "lofty",
      label: "Lofty CRM",
      apiKeyEnv: "LOFTY_API_KEY",
      baseUrl: "https://api.lofty.com",
      authType: "header",
      authHeader: "Authorization",
      authPrefix: "token ",
      authQueryParam: "",
      endpoints: {
        leads: "/v1.0/leads",
        lead: "/v1.0/leads/:id",
        notes: "/v2.0/leads/:id/activities",
      },
      dbColumns: {
        leadId: "id",
        stage: "stage",
        tags: "tags",
      },
    },
  },
  {
    slug: "followupboss",
    label: "Follow Up Boss",
    description: "Basic auth: API key as username, blank password.",
    helpUrl: "https://help.followupboss.com/hc/en-us/articles/360014289393",
    helpText: "Admin → API. Each user has a unique key.",
    keyLabel: "Follow Up Boss API Key",
    logo: "https://logo.clearbit.com/followupboss.com",
    template: {
      provider: "followupboss",
      label: "Follow Up Boss",
      apiKeyEnv: "FUB_API_KEY",
      baseUrl: "https://api.followupboss.com/v1",
      authType: "basic",
      authHeader: "Authorization",
      authPrefix: "",
      authQueryParam: "",
      endpoints: {
        leads: "/people",
        lead: "/people/:id",
        notes: "/notes",
      },
      dbColumns: {
        leadId: "id",
        stage: "stage",
        tags: "tags",
      },
    },
  },
  {
    slug: "sierra",
    label: "Sierra Interactive",
    description: "Custom Sierra-ApiKey header.",
    helpUrl: "https://help.sierrainteractive.com/helpcenter/unlock-new-opportunities-with-the-sierra-api",
    helpText: "Gear icon → Integrations → Sierra Interactive → Copy API Key.",
    keyLabel: "Sierra API Key",
    logo: "https://logo.clearbit.com/sierrainteractive.com",
    template: {
      provider: "sierra",
      label: "Sierra Interactive",
      apiKeyEnv: "SIERRA_API_KEY",
      baseUrl: "https://api.sierrainteractivedev.com",
      authType: "header",
      authHeader: "Sierra-ApiKey",
      authPrefix: "",
      authQueryParam: "",
      endpoints: {
        leads: "/leads/Get",
        lead: "/leads/Get/:id",
        notes: "/leads/AddNote",
      },
      dbColumns: {
        leadId: "id",
        stage: "leadType",
        tags: "tags",
      },
    },
  },
  {
    slug: "boldtrail",
    label: "BoldTrail",
    description: "Bearer token. Tokens expire after 12 months — renew yearly.",
    helpUrl: "https://help.insiderealestate.com/en/articles/4263959-boldtrail-api-tokens",
    helpText: "Lead Engine → Lead Dropbox → choose scope → Generate token. Up to 3 tokens per account.",
    keyLabel: "BoldTrail API Token",
    logo: "https://logo.clearbit.com/boldtrail.com",
    notice: "BoldTrail tokens expire after 12 months. Set a calendar reminder to regenerate.",
    template: {
      provider: "boldtrail",
      label: "BoldTrail",
      apiKeyEnv: "BOLDTRAIL_API_TOKEN",
      baseUrl: "https://api.boldtrail.com",
      authType: "header",
      authHeader: "Authorization",
      authPrefix: "Bearer ",
      authQueryParam: "",
      endpoints: {
        leads: "/v2/contacts",
        lead: "/v2/contacts/:id",
        notes: "/v2/contacts/:id/notes",
      },
      dbColumns: {
        leadId: "id",
        stage: "stage",
        tags: "tags",
      },
    },
  },
  {
    slug: "brivity",
    label: "Brivity",
    description: "Token-based auth, Rails style. Account owners only can generate keys.",
    helpUrl: "https://nvntd.github.io/brivity-core/doc/api/index.html",
    helpText: "Settings → Business. Account owner role required to issue API keys.",
    keyLabel: "Brivity API Key",
    logo: "https://logo.clearbit.com/brivity.com",
    notice: "Brivity API keys can only be generated by the account owner. Team agents need owner help.",
    template: {
      provider: "brivity",
      label: "Brivity",
      apiKeyEnv: "BRIVITY_API_KEY",
      baseUrl: "https://www.brivity.com",
      authType: "header",
      authHeader: "Authorization",
      authPrefix: "Token token=",
      authQueryParam: "",
      endpoints: {
        leads: "/api/v2/leads",
        lead: "/api/people/:id",
        notes: "/api/v2/notes",
      },
      dbColumns: {
        leadId: "id",
        stage: "stage",
        tags: "tags",
      },
    },
  },
];

export function findPresetForForm(form: CrmIntegrationForm | null): CrmPreset | null {
  if (!form) return null;
  return CRM_PRESETS.find((p) => p.template.provider === form.provider) ?? null;
}

export function applyPreset(
  preset: CrmPreset,
  current: CrmIntegrationForm | null,
): CrmIntegrationForm {
  const carry = current ?? ({} as Partial<CrmIntegrationForm>);
  return {
    ...preset.template,
    apiKey: carry.apiKey ?? "",
    hasApiKey: base.hasApiKey,
    apiKeyPreview: base.apiKeyPreview,
  };
}
