-- 0007_memory_store.sql — holographic memory store, PG port.
--
-- Brings the entire schema of ~/.elevate/memory_store.db into the
-- central operational DB so the elevate-memory-store plugin can stop
-- opening its own sqlite3 file.
--
-- Design notes:
--
-- 1. **Vectors as bytea, not pgvector(N).** The plugin currently stores
--    HRR phase vectors and embedding vectors as raw byte blobs, decoded
--    in Python with struct.unpack / hrr.bytes_to_phases. Keeping them
--    as bytea is a zero-change swap on the Python side. pgvector is
--    enabled here so we can later move to native vector(N) columns
--    + HNSW indexes without another migration, but that's out of scope
--    for the SQLite cutover.
--
-- 2. **FTS5 → tsvector + GIN.** Sqlite FTS5 virtual tables are replaced
--    with a `search_tsv` column on each searchable base table plus a
--    BEFORE INSERT/UPDATE trigger that recomputes the vector. Search
--    queries swap `WHERE x_fts MATCH ?` for
--    `WHERE search_tsv @@ websearch_to_tsquery('english', %s)`.
--
-- 3. **Names preserved exactly.** No column renames so the eventual
--    store.py rewrite is a sqlite3 → psycopg connection swap plus
--    FTS-MATCH rewrites, nothing more.
--
-- 4. **AUTOINCREMENT → IDENTITY.** PG 10+ IDENTITY is the modern
--    equivalent and survives pg_dump roundtrips correctly. Sequence
--    values will be reseeded by the data migration to preserve
--    existing IDs (see _pg_memory_migrate.py).

CREATE EXTENSION IF NOT EXISTS vector;

-- ───── facts ────────────────────────────────────────────────────────
CREATE TABLE memory_facts (
    fact_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content         TEXT NOT NULL UNIQUE,
    category        TEXT DEFAULT 'general',
    tags            TEXT DEFAULT '',
    trust_score     DOUBLE PRECISION DEFAULT 0.5,
    retrieval_count INTEGER DEFAULT 0,
    helpful_count   INTEGER DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    hrr_vector      BYTEA,
    source_type     TEXT DEFAULT '',
    source_uri      TEXT DEFAULT '',
    source_excerpt  TEXT DEFAULT '',
    observed_at     TIMESTAMP,
    memory_space    TEXT DEFAULT '',
    status          TEXT DEFAULT 'active',
    superseded_by   BIGINT,
    search_tsv      TSVECTOR
);
CREATE INDEX idx_memory_facts_trust    ON memory_facts(trust_score DESC);
CREATE INDEX idx_memory_facts_category ON memory_facts(category);
CREATE INDEX idx_memory_facts_search   ON memory_facts USING GIN(search_tsv);

CREATE OR REPLACE FUNCTION memory_facts_tsv_refresh()
RETURNS trigger AS $$
BEGIN
    NEW.search_tsv :=
        setweight(to_tsvector('english', coalesce(NEW.content, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.tags, '')),    'B');
    RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_memory_facts_tsv
BEFORE INSERT OR UPDATE OF content, tags
ON memory_facts
FOR EACH ROW EXECUTE FUNCTION memory_facts_tsv_refresh();

-- ───── entities ─────────────────────────────────────────────────────
CREATE TABLE memory_entities (
    entity_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    entity_type TEXT DEFAULT 'unknown',
    aliases     TEXT DEFAULT '',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_memory_entities_name ON memory_entities(name);

-- ───── fact_entities (M:N) ──────────────────────────────────────────
CREATE TABLE memory_fact_entities (
    fact_id   BIGINT NOT NULL REFERENCES memory_facts(fact_id) ON DELETE CASCADE,
    entity_id BIGINT NOT NULL REFERENCES memory_entities(entity_id) ON DELETE CASCADE,
    PRIMARY KEY (fact_id, entity_id)
);

-- ───── banks (per-category bundled vectors) ─────────────────────────
CREATE TABLE memory_banks (
    bank_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name  TEXT NOT NULL UNIQUE,
    vector     BYTEA NOT NULL,
    dim        INTEGER NOT NULL,
    fact_count INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ───── embeddings (per-document/chunk/fact) ─────────────────────────
CREATE TABLE memory_embeddings (
    embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type  TEXT NOT NULL,
    target_id    BIGINT NOT NULL,
    provider     TEXT NOT NULL,
    model        TEXT NOT NULL,
    dimensions   INTEGER NOT NULL,
    content_hash TEXT NOT NULL,
    vector       BYTEA NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(target_type, target_id, provider, model)
);
CREATE INDEX idx_memory_embeddings_target
    ON memory_embeddings(target_type, target_id);
CREATE INDEX idx_memory_embeddings_provider_model
    ON memory_embeddings(provider, model);

-- ───── turn journal ─────────────────────────────────────────────────
CREATE TABLE memory_turn_journal (
    turn_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        TEXT DEFAULT '',
    turn_hash         TEXT NOT NULL UNIQUE,
    user_content      TEXT NOT NULL,
    assistant_content TEXT NOT NULL,
    status            TEXT DEFAULT 'pending',
    extracted_count   INTEGER DEFAULT 0,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_at      TIMESTAMP,
    session_day       TEXT NOT NULL DEFAULT ''
);
CREATE INDEX idx_memory_turn_journal_status
    ON memory_turn_journal(status, created_at);
CREATE INDEX idx_memory_turn_journal_session
    ON memory_turn_journal(session_id, status);

-- ───── documents ────────────────────────────────────────────────────
CREATE TABLE memory_documents (
    document_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type   TEXT NOT NULL DEFAULT '',
    source_uri    TEXT NOT NULL UNIQUE,
    title         TEXT DEFAULT '',
    metadata_json TEXT DEFAULT '',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_memory_documents_source
    ON memory_documents(source_type, source_uri);

-- ───── chunks (FTS) ─────────────────────────────────────────────────
CREATE TABLE memory_chunks (
    chunk_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id    BIGINT NOT NULL REFERENCES memory_documents(document_id) ON DELETE CASCADE,
    chunk_index    INTEGER NOT NULL,
    content        TEXT NOT NULL,
    char_count     INTEGER DEFAULT 0,
    source_excerpt TEXT DEFAULT '',
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    search_tsv     TSVECTOR,
    UNIQUE(document_id, chunk_index)
);
CREATE INDEX idx_memory_chunks_document
    ON memory_chunks(document_id, chunk_index);
CREATE INDEX idx_memory_chunks_search
    ON memory_chunks USING GIN(search_tsv);

CREATE OR REPLACE FUNCTION memory_chunks_tsv_refresh()
RETURNS trigger AS $$
BEGIN
    NEW.search_tsv :=
        setweight(to_tsvector('english', coalesce(NEW.content, '')),       'A') ||
        setweight(to_tsvector('english', coalesce(NEW.source_excerpt, '')),'B');
    RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_memory_chunks_tsv
BEFORE INSERT OR UPDATE OF content, source_excerpt
ON memory_chunks
FOR EACH ROW EXECUTE FUNCTION memory_chunks_tsv_refresh();

-- ───── events ───────────────────────────────────────────────────────
CREATE TABLE memory_events (
    event_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  TEXT DEFAULT '',
    event       TEXT NOT NULL,
    detail_json TEXT DEFAULT '',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_memory_events_session
    ON memory_events(session_id, created_at);
CREATE INDEX idx_memory_events_event
    ON memory_events(event, created_at);

-- ───── injections (audit log) ───────────────────────────────────────
CREATE TABLE memory_injections (
    injection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   TEXT DEFAULT '',
    query        TEXT DEFAULT '',
    content      TEXT DEFAULT '',
    fact_ids     TEXT DEFAULT '',
    chunk_ids    TEXT DEFAULT '',
    source       TEXT DEFAULT '',
    prompt_chars INTEGER DEFAULT 0,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_memory_injections_session
    ON memory_injections(session_id, created_at);

-- ───── gaps ─────────────────────────────────────────────────────────
CREATE TABLE memory_gaps (
    gap_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      TEXT DEFAULT '',
    query           TEXT DEFAULT '',
    candidate_count INTEGER DEFAULT 0,
    note            TEXT DEFAULT '',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_memory_gaps_session
    ON memory_gaps(session_id, created_at);

-- ───── fact_links (fact → fact) ─────────────────────────────────────
CREATE TABLE memory_fact_links (
    source_fact_id BIGINT NOT NULL REFERENCES memory_facts(fact_id) ON DELETE CASCADE,
    target_fact_id BIGINT NOT NULL REFERENCES memory_facts(fact_id) ON DELETE CASCADE,
    link_type      TEXT DEFAULT 'relates_to',
    weight         DOUBLE PRECISION DEFAULT 1.0,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (source_fact_id, target_fact_id, link_type)
);
CREATE INDEX idx_memory_fact_links_source ON memory_fact_links(source_fact_id);
CREATE INDEX idx_memory_fact_links_target ON memory_fact_links(target_fact_id);

-- ───── clusters ─────────────────────────────────────────────────────
CREATE TABLE memory_clusters (
    cluster_id    TEXT PRIMARY KEY,
    name          TEXT DEFAULT '',
    tags          TEXT DEFAULT '',
    fact_ids_json TEXT NOT NULL DEFAULT '[]',
    source        TEXT DEFAULT 'auto',
    weight        DOUBLE PRECISION DEFAULT 1.0,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_memory_clusters_updated
    ON memory_clusters(updated_at);

CREATE TABLE memory_cluster_members (
    cluster_id TEXT NOT NULL REFERENCES memory_clusters(cluster_id) ON DELETE CASCADE,
    fact_id    BIGINT NOT NULL REFERENCES memory_facts(fact_id) ON DELETE CASCADE,
    weight     DOUBLE PRECISION DEFAULT 1.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (cluster_id, fact_id)
);
CREATE INDEX idx_memory_cluster_members_fact
    ON memory_cluster_members(fact_id);

-- ───── modal assets (audio/video/image hooks) ───────────────────────
CREATE TABLE memory_modal_assets (
    asset_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id   BIGINT NOT NULL REFERENCES memory_documents(document_id) ON DELETE CASCADE,
    asset_type    TEXT DEFAULT 'text',
    locator       TEXT DEFAULT '',
    summary       TEXT DEFAULT '',
    text_content  TEXT DEFAULT '',
    metadata_json TEXT DEFAULT '{}',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_memory_modal_assets_document
    ON memory_modal_assets(document_id, asset_type);

-- ───── chunk → entity (M:N) ─────────────────────────────────────────
CREATE TABLE memory_chunk_entities (
    chunk_id  BIGINT NOT NULL REFERENCES memory_chunks(chunk_id) ON DELETE CASCADE,
    entity_id BIGINT NOT NULL REFERENCES memory_entities(entity_id) ON DELETE CASCADE,
    weight    DOUBLE PRECISION DEFAULT 1.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (chunk_id, entity_id)
);
CREATE INDEX idx_memory_chunk_entities_entity
    ON memory_chunk_entities(entity_id);

-- ───── relations (entity → entity, co-occurrence) ──────────────────
CREATE TABLE memory_relations (
    relation_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_entity_id BIGINT NOT NULL REFERENCES memory_entities(entity_id) ON DELETE CASCADE,
    target_entity_id BIGINT NOT NULL REFERENCES memory_entities(entity_id) ON DELETE CASCADE,
    relation_type    TEXT DEFAULT 'co_occurs_with',
    source_type      TEXT DEFAULT '',
    source_id        BIGINT DEFAULT 0,
    weight           DOUBLE PRECISION DEFAULT 1.0,
    evidence         TEXT DEFAULT '',
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(source_entity_id, target_entity_id, relation_type, source_type, source_id)
);
CREATE INDEX idx_memory_relations_source
    ON memory_relations(source_entity_id, relation_type);
CREATE INDEX idx_memory_relations_target
    ON memory_relations(target_entity_id, relation_type);

-- ───── community reports (cluster summaries, FTS) ───────────────────
CREATE TABLE memory_community_reports (
    community_id   TEXT PRIMARY KEY REFERENCES memory_clusters(cluster_id) ON DELETE CASCADE,
    name           TEXT DEFAULT '',
    summary        TEXT DEFAULT '',
    tags           TEXT DEFAULT '',
    entity_names   TEXT DEFAULT '',
    fact_ids_json  TEXT DEFAULT '[]',
    chunk_ids_json TEXT DEFAULT '[]',
    source         TEXT DEFAULT 'cluster',
    weight         DOUBLE PRECISION DEFAULT 1.0,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    search_tsv     TSVECTOR
);
CREATE INDEX idx_memory_community_reports_search
    ON memory_community_reports USING GIN(search_tsv);

CREATE OR REPLACE FUNCTION memory_community_reports_tsv_refresh()
RETURNS trigger AS $$
BEGIN
    NEW.search_tsv :=
        setweight(to_tsvector('english', coalesce(NEW.name, '')),         'A') ||
        setweight(to_tsvector('english', coalesce(NEW.summary, '')),      'A') ||
        setweight(to_tsvector('english', coalesce(NEW.tags, '')),         'B') ||
        setweight(to_tsvector('english', coalesce(NEW.entity_names, '')), 'C');
    RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_memory_community_reports_tsv
BEFORE INSERT OR UPDATE OF name, summary, tags, entity_names
ON memory_community_reports
FOR EACH ROW EXECUTE FUNCTION memory_community_reports_tsv_refresh();
